FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# uninstall the current bcrypt modules
RUN npm uninstall bcrypt

# install the bcrypt modules for the machine
RUN npm install bcrypt

# Copy the rest of the application
COPY . .
EXPOSE 3000

CMD ["npm", "run", "start:dev"]
