FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# uninstall the current bcrypt modules
RUN npm uninstall bcrypt

# install the bcrypt modules for the machine
RUN npm install bcrypt

# Copy the rest of the application
COPY . .

# Install wait-for-it script
RUN apk add --no-cache bash

EXPOSE 3000

# Default command is now in docker-compose.yml
